-- Step 1: Add new Role enum values (must commit before using)
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'RECEPTION';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ACCOUNTANT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'EMPLOYEE';
