"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";
import { fetchPublicSettings } from "@/lib/services/cmsService";
import type { HospitalSettings } from "@/types/cms";
import { HOSPITAL_INFO, STATS } from "@/lib/config/siteConfig";

// Fallback defaults from siteConfig so the site works even before DB is seeded
const DEFAULTS: HospitalSettings = {
  hospital_name_bn: HOSPITAL_INFO.nameBn,
  hospital_name_en: HOSPITAL_INFO.nameEn,
  logo_url:         "",
  tagline_bn:       HOSPITAL_INFO.taglineBn,
  tagline_en:       HOSPITAL_INFO.taglineEn,
  phone:            HOSPITAL_INFO.phone,
  emergency:        HOSPITAL_INFO.emergency,
  email:            HOSPITAL_INFO.email,
  address_bn:       HOSPITAL_INFO.addressBn,
  address_en:       HOSPITAL_INFO.addressEn,
  map_embed_url:    HOSPITAL_INFO.mapEmbedUrl,
  hours_bn:         HOSPITAL_INFO.hoursBn,
  hours_en:         HOSPITAL_INFO.hoursEn,
  friday_bn:        HOSPITAL_INFO.fridayBn,
  friday_en:        HOSPITAL_INFO.fridayEn,
  social_facebook:  HOSPITAL_INFO.socialFacebook,
  social_youtube:   HOSPITAL_INFO.socialYoutube,
  social_instagram: "",
  hero_badge_bn:    "শেরপুরের আধুনিক চক্ষু সেবা কেন্দ্র",
  hero_badge_en:    "Modern Eye Care Center in Sherpur",
  hero_title_bn:    "আপনার দৃষ্টিশক্তি আমাদের দায়িত্ব",
  hero_title_en:    "Your Vision, Our Responsibility",
  hero_desc_bn:     "শেরপুর আধুনিক চক্ষু হাসপাতালে আমরা সর্বাধুনিক প্রযুক্তি ও অভিজ্ঞ চিকিৎসকদের মাধ্যমে আপনার চোখের সর্বোত্তম যত্ন নিশ্চিত করি।",
  hero_desc_en:     "At Sherpur Adhunik Eye Hospital, we ensure the best care for your eyes through modern technology and experienced doctors.",
  hero_image_url:   "",
  stat1_value_bn:   STATS[0].valueBn,  stat1_value_en: STATS[0].valueEn,
  stat1_label_bn:   STATS[0].labelBn,  stat1_label_en: STATS[0].labelEn,
  stat2_value_bn:   STATS[1].valueBn,  stat2_value_en: STATS[1].valueEn,
  stat2_label_bn:   STATS[1].labelBn,  stat2_label_en: STATS[1].labelEn,
  stat3_value_bn:   STATS[2].valueBn,  stat3_value_en: STATS[2].valueEn,
  stat3_label_bn:   STATS[2].labelBn,  stat3_label_en: STATS[2].labelEn,
  stat4_value_bn:   STATS[3].valueBn,  stat4_value_en: STATS[3].valueEn,
  stat4_label_bn:   STATS[3].labelBn,  stat4_label_en: STATS[3].labelEn,
  about_title_bn:   "আমাদের সম্পর্কে",
  about_title_en:   "About Us",
  about_desc_bn:    "শেরপুর আধুনিক চক্ষু হাসপাতাল শেরপুর জেলার মানুষের চোখের সেবায় নিবেদিত।",
  about_desc_en:    "Sherpur Adhunik Eye Hospital is dedicated to eye care for the people of Sherpur district.",
  about_mission_bn: "সাশ্রয়ী মূল্যে সর্বোচ্চ মানের চক্ষু সেবা প্রদান করা।",
  about_mission_en: "To provide the highest quality eye care at affordable prices.",
  about_vision_bn:  "শেরপুর জেলায় অন্ধত্বমুক্ত সমাজ গড়ে তোলা।",
  about_vision_en:  "To build a blindness-free society in Sherpur district.",
  about_main_image:  "",
  about_env_image_1: "",
  about_env_image_2: "",
  about_env_image_3: "",
  about_env_image_4: "",
  about_gallery_1:   "",
  about_gallery_2:   "",
  about_gallery_3:   "",
  about_gallery_4:   "",
  about_gallery_5:   "",
  about_gallery_6:   "",
  about_founded_bn:     "প্রতিষ্ঠাকাল: [সাল]",
  about_founded_en:     "Established: [Year]",
  about_location_bn:    "শেরপুর সদর, শেরপুর",
  about_location_en:    "Sherpur Sadar, Sherpur",
  about_tag_bn:         "আমাদের পরিচয়",
  about_tag_en:         "Who We Are",
  about_intro_title_bn: "শেরপুর আধুনিক চক্ষু হাসপাতাল ও ফ্যাকো সেন্টার",
  about_intro_title_en: "Sherpur Adhunik Eye Hospital & Phaco Center",
  about_para1_bn:       "শেরপুর আধুনিক চক্ষু হাসপাতাল ও ফ্যাকো সেন্টার শেরপুর জেলার মানুষের চোখের সেবায় নিবেদিত একটি বিশেষায়িত চিকিৎসা প্রতিষ্ঠান।",
  about_para1_en:       "Sherpur Adhunik Eye Hospital & Phaco Center is a specialized medical institution dedicated to eye care for the people of Sherpur district.",
  about_para2_bn:       "আমাদের হাসপাতালে অভিজ্ঞ চক্ষু বিশেষজ্ঞ চিকিৎসক দল, আধুনিক ডায়াগনস্টিক যন্ত্রপাতি এবং সর্বোচ্চ মানের চিকিৎসা সেবা নিশ্চিত করা হয়।",
  about_para2_en:       "Our hospital ensures an experienced team of eye specialists, modern diagnostic equipment, and the highest quality medical care.",
  hero_about_image:       "",
  hero_appointment_image: "",
  hero_doctors_image:     "",
  hero_gallery_image:     "",
  hero_services_image:    "",
  hero_news_image:        "",
  hero_contact_image:     "",
  // Home icons
  icon_service_1: "👁️", icon_service_2: "🔬", icon_service_3: "👓",
  icon_service_4: "💧", icon_service_5: "🧒", icon_service_6: "🏥",
  icon_why_1: "🏆", icon_why_2: "⚙️", icon_why_3: "💙",
  icon_why_4: "💰", icon_why_5: "🕐", icon_why_6: "📍",
  icon_facility_1: "🏨", icon_facility_2: "🔭", icon_facility_3: "🛏️",
  icon_facility_4: "🚑", icon_facility_5: "💊", icon_facility_6: "🅿️",
  // About icons
  icon_mission: "🎯", icon_vision: "🌟",
  icon_value_1: "❤️", icon_value_2: "✅", icon_value_3: "🤝",
  icon_value_4: "🌱", icon_value_5: "🏘️", icon_value_6: "📚",
  icon_care_1: "👂", icon_care_2: "🔍", icon_care_3: "💬", icon_care_4: "🔄",
  icon_equip_1: "🔭", icon_equip_2: "📊", icon_equip_3: "💧",
  icon_equip_4: "⚡", icon_equip_5: "🌐", icon_equip_6: "🔬",
  icon_contact_1: "🚨", icon_contact_2: "📅", icon_contact_3: "👓",
  icon_contact_4: "🧒", icon_contact_5: "🌙", icon_contact_6: "💧",
  // Nav icons
  nav_icon_home:        "",
  nav_icon_about:       "",
  nav_icon_doctors:     "",
  nav_icon_services:    "",
  nav_icon_appointment: "",
  nav_icon_gallery:     "",
  nav_icon_news:        "",
  nav_icon_contact:     "",
};

interface SiteSettingsCtx {
  s: HospitalSettings;
  loading: boolean;
}

const Ctx = createContext<SiteSettingsCtx>({ s: DEFAULTS, loading: true });

export function SiteSettingsProvider({ children }: { children: ReactNode }) {
  const [s, setS] = useState<HospitalSettings>(DEFAULTS);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchPublicSettings()
      .then((map) => {
        const mapped: Partial<HospitalSettings> = {
          ...map,
          // Hospital
          hospital_name_bn: map.hospital_name_bn || "",
          hospital_name_en: map.hospital_name_en || "",
          logo_url:         map.hospital_logo    || "",
          tagline_bn:       map.hospital_tagline_bn || "",
          tagline_en:       map.hospital_tagline_en || "",
          // Contact
          phone:         map.contact_phone      || map.phone         || "",
          email:         map.contact_email      || map.email         || "",
          address_bn:    map.contact_address_bn || map.address_bn    || "",
          address_en:    map.contact_address_en || map.address_en    || "",
          map_embed_url: map.contact_map_url    || map.map_embed_url || "",
          // Hours
          hours_bn:  map.hours_weekday_bn || "",
          hours_en:  map.hours_weekday_en || "",
          friday_bn: map.hours_weekend_bn || "",
          friday_en: map.hours_weekend_en || "",
          emergency: map.hours_emergency  || "",
          // Social
          social_facebook:  map.social_facebook  || "",
          social_youtube:   map.social_youtube   || "",
          social_instagram: map.social_instagram || "",
          // Hero
          hero_image_url: map.hero_image    || "",
          hero_badge_bn:  map.hero_badge_bn || "",
          hero_badge_en:  map.hero_badge_en || "",
          hero_title_bn:  map.hero_title_bn || "",
          hero_title_en:  map.hero_title_en || "",
          hero_desc_bn:   map.hero_desc_bn  || "",
          hero_desc_en:   map.hero_desc_en  || "",
          // Stats
          stat1_value_bn: map.stat1_value_bn || "",
          stat1_value_en: map.stat1_value_en || "",
          stat1_label_bn: map.stat1_label_bn || "",
          stat1_label_en: map.stat1_label_en || "",
          stat2_value_bn: map.stat2_value_bn || "",
          stat2_value_en: map.stat2_value_en || "",
          stat2_label_bn: map.stat2_label_bn || "",
          stat2_label_en: map.stat2_label_en || "",
          stat3_value_bn: map.stat3_value_bn || "",
          stat3_value_en: map.stat3_value_en || "",
          stat3_label_bn: map.stat3_label_bn || "",
          stat3_label_en: map.stat3_label_en || "",
          stat4_value_bn: map.stat4_value_bn || "",
          stat4_value_en: map.stat4_value_en || "",
          stat4_label_bn: map.stat4_label_bn || "",
          stat4_label_en: map.stat4_label_en || "",
          // About text
          about_title_bn:       map.about_title_bn       || "",
          about_title_en:       map.about_title_en       || "",
          about_tag_bn:         map.about_tag_bn         || "",
          about_tag_en:         map.about_tag_en         || "",
          about_intro_title_bn: map.about_intro_title_bn || "",
          about_intro_title_en: map.about_intro_title_en || "",
          about_para1_bn:       map.about_para1_bn       || "",
          about_para1_en:       map.about_para1_en       || "",
          about_para2_bn:       map.about_para2_bn       || "",
          about_para2_en:       map.about_para2_en       || "",
          about_founded_bn:     map.about_founded_bn     || "",
          about_founded_en:     map.about_founded_en     || "",
          about_location_bn:    map.about_location_bn    || "",
          about_location_en:    map.about_location_en    || "",
          about_mission_bn:     map.about_mission_bn     || "",
          about_mission_en:     map.about_mission_en     || "",
          about_vision_bn:      map.about_vision_bn      || "",
          about_vision_en:      map.about_vision_en      || "",
          about_desc_bn:        map.about_desc_bn        || "",
          about_desc_en:        map.about_desc_en        || "",
          // About images
          about_main_image:  map.about_image_1    || "",
          about_gallery_1:   map.about_image_2    || "",
          about_gallery_2:   map.about_image_3    || "",
          about_gallery_3:   map.about_image_4    || "",
          about_gallery_4:   map.about_image_5    || "",
          about_gallery_5:   map.about_image_6    || "",
          about_gallery_6:   map.about_image_7    || "",
          about_env_image_1: map.about_env_image_1 || "",
          about_env_image_2: map.about_env_image_2 || "",
          about_env_image_3: map.about_env_image_3 || "",
          about_env_image_4: map.about_env_image_4 || "",
          // Page heroes
          hero_about_image:       map.hero_about_image       || "",
          hero_appointment_image: map.hero_appointment_image || "",
          hero_doctors_image:     map.hero_doctors_image     || "",
          hero_gallery_image:     map.hero_gallery_image     || "",
          hero_services_image:    map.hero_services_image    || "",
          hero_news_image:        map.hero_news_image        || "",
          hero_contact_image:     map.hero_contact_image     || "",
          // Nav icons
          nav_icon_home:        map.nav_icon_home        || "",
          nav_icon_about:       map.nav_icon_about       || "",
          nav_icon_doctors:     map.nav_icon_doctors     || "",
          nav_icon_services:    map.nav_icon_services    || "",
          nav_icon_appointment: map.nav_icon_appointment || "",
          nav_icon_gallery:     map.nav_icon_gallery     || "",
          nav_icon_news:        map.nav_icon_news        || "",
          nav_icon_contact:     map.nav_icon_contact     || "",
          // Home icons
          icon_service_1: map.icon_service_1 || "",
          icon_service_2: map.icon_service_2 || "",
          icon_service_3: map.icon_service_3 || "",
          icon_service_4: map.icon_service_4 || "",
          icon_service_5: map.icon_service_5 || "",
          icon_service_6: map.icon_service_6 || "",
          icon_why_1: map.icon_why_1 || "",
          icon_why_2: map.icon_why_2 || "",
          icon_why_3: map.icon_why_3 || "",
          icon_why_4: map.icon_why_4 || "",
          icon_why_5: map.icon_why_5 || "",
          icon_why_6: map.icon_why_6 || "",
          icon_facility_1: map.icon_facility_1 || "",
          icon_facility_2: map.icon_facility_2 || "",
          icon_facility_3: map.icon_facility_3 || "",
          icon_facility_4: map.icon_facility_4 || "",
          icon_facility_5: map.icon_facility_5 || "",
          icon_facility_6: map.icon_facility_6 || "",
          // About icons
          icon_mission: map.icon_mission || "",
          icon_vision:  map.icon_vision  || "",
          icon_value_1: map.icon_value_1 || "",
          icon_value_2: map.icon_value_2 || "",
          icon_value_3: map.icon_value_3 || "",
          icon_value_4: map.icon_value_4 || "",
          icon_value_5: map.icon_value_5 || "",
          icon_value_6: map.icon_value_6 || "",
          icon_care_1: map.icon_care_1 || "",
          icon_care_2: map.icon_care_2 || "",
          icon_care_3: map.icon_care_3 || "",
          icon_care_4: map.icon_care_4 || "",
          icon_equip_1: map.icon_equip_1 || "",
          icon_equip_2: map.icon_equip_2 || "",
          icon_equip_3: map.icon_equip_3 || "",
          icon_equip_4: map.icon_equip_4 || "",
          icon_equip_5: map.icon_equip_5 || "",
          icon_equip_6: map.icon_equip_6 || "",
          icon_contact_1: map.icon_contact_1 || "",
          icon_contact_2: map.icon_contact_2 || "",
          icon_contact_3: map.icon_contact_3 || "",
          icon_contact_4: map.icon_contact_4 || "",
          icon_contact_5: map.icon_contact_5 || "",
          icon_contact_6: map.icon_contact_6 || "",
        };
        setS({ ...DEFAULTS, ...mapped } as HospitalSettings);
      })
      .catch(() => {/* keep defaults */})
      .finally(() => setLoading(false));
  }, []);

  return <Ctx.Provider value={{ s, loading }}>{children}</Ctx.Provider>;
}

export function useSiteSettings() {
  return useContext(Ctx);
}
